apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-postgresql
  namespace: m
spec:
  serviceName: "auth-postgresql"
  replicas: 1
  selector:
    matchLabels:
      app: auth-postgresql
  template:
    metadata:
      labels:
        app: auth-postgresql
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          envFrom:
            - secretRef:
                name: auth-db-secret
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-postgresql
  namespace: m
spec:
  serviceName: "user-postgresql"
  replicas: 1
  selector:
    matchLabels:
      app: user-postgresql
  template:
    metadata:
      labels:
        app: user-postgresql
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          envFrom:
            - secretRef:
                name: user-db-secret
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: route-postgresql
  namespace: m
spec:
  serviceName: "route-postgresql"
  replicas: 1
  selector:
    matchLabels:
      app: route-postgresql
  template:
    metadata:
      labels:
        app: route-postgresql
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          envFrom:
            - secretRef:
                name: route-db-secret
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi


---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: booking-postgresql
  namespace: m
spec:
  serviceName: "booking-postgresql"
  replicas: 1
  selector:
    matchLabels:
      app: booking-postgresql
  template:
    metadata:
      labels:
        app: booking-postgresql
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          envFrom:
            - secretRef:
                name: booking-db-secret
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi
