apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: m
spec:
  selector:
    app: auth-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: jwt-validator
  namespace: m
spec:
  selector:
    app: jwt-validator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: m
spec:
  selector:
    app: user-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
