apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-postgresql
  namespace: m
spec:
  serviceName: "auth-postgresql"
  replicas: 1
  selector:
    matchLabels:
      app: auth-postgresql
  template:
    metadata:
      labels:
        app: auth-postgresql
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          envFrom:
            - secretRef:
                name: auth-db-secret
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: crud-postgresql
  namespace: m
spec:
  serviceName: "crud-postgresql"
  replicas: 1
  selector:
    matchLabels:
      app: crud-postgresql
  template:
    metadata:
      labels:
        app: crud-postgresql
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          envFrom:
            - secretRef:
                name: crud-db-secret
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
