apiVersion: v1
kind: ConfigMap
metadata:
  name: migrations-config
  namespace: m
data:
  dump.sql: |
    CREATE TABLE users
    (
        id         SERIAL PRIMARY KEY,
        username   VARCHAR(50)         NOT NULL,
        first_name VARCHAR(50),
        last_name  VARCHAR(50),
        email      VARCHAR(100) UNIQUE NOT NULL,
        phone      VARCHAR(15)
    );