apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: m
spec:
  selector:
    app: auth-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: m
spec:
  selector:
    app: user-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: auth-postgresql
  namespace: m
spec:
  selector:
    app: auth-postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: user-postgresql
  namespace: m
spec:
  selector:
    app: user-postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
