networks:
  default:
    name: hw_06

services:
  app:
    container_name: auth_service
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}

      - JWT_SECRET=${JWT_SECRET}
    restart: always
    depends_on:
      - postgresql
      - pgadmin

  jwt-app:
    container_name: jwt_verifier
    build:
      context: ../jwt_verifier
      dockerfile: ./Dockerfile
    ports:
      - "8088:8088"
    environment:
      - JWT_SECRET=${JWT_SECRET}
    restart: always
    depends_on:
      - app

  postgresql:
    image: postgres:latest
    container_name: postgresql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=auth_db,user_db
    ports:
      - "5435:5432"
    restart: always
    volumes:
      - ./schema/dump.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    restart: always
    depends_on:
      - postgresql
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
