apiVersion: v1
kind: ConfigMap
metadata:
  name: route-app-config
  namespace: m
data:
  SERVER_PORT: "8082"
  DB_USER: "root"
  DB_PASSWORD: "pass"
  DB_HOST: "route-postgresql"
  DB_PORT: "5432"
  DB_NAME: "routes"
  KAFKA_BROKERS: "kafka:9092"
  KAFKA_TOPIC: "route-events"
