apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app
  namespace: m
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
        - name: app
          image: nislovskaya/hw_06-user:latest
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: user-app-config
            - secretRef:
                name: user-db-secret
          livenessProbe:
            httpGet:
              path: /user/health
              port: 8081
          readinessProbe:
            httpGet:
              path: /user/health
              port: 8081
