apiVersion: v1
kind: Secret
metadata:
  name: user-db-secret
  namespace: m
type: Opaque
data:
  POSTGRES_PASSWORD: "cGFzcw=="
  POSTGRES_USER: "cm9vdA=="
  POSTGRES_DB: "dXNlcnM="
  DB_PASSWORD: "cGFzcw=="
  DB_USER: "cm9vdA=="
  DB_NAME: "dXNlcnM="
